services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST:-0.0.0.0}:3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      test: ["CMD", "/app/personal-api", "--health-check"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    labels:
      - "com.personal-api.description=Personal API Service"
      - "com.personal-api.environment=production"
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
    name: personal-api-network