services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST:-0.0.0.0}:3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - api-network

networks:
  api-network:
    driver: bridge